name: CI

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
build-linux:
name: Build Linux
runs-on: ubuntu-latest
env: { CI: true }
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: '18'
- name: Cache node modules
uses: actions/cache@v4
with:
path: |
/node_modules
~/.npm
key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
restore-keys: |
${{ runner.os }}-node-
- name: Install
run: npm ci
- name: Build frontend
run: npm run build-frontend
- name: Build Linux package
run: npm run build-l
- name: Upload Linux artifacts
uses: actions/upload-artifact@v4
with:
name: linux-dist
path: dist/**

build-windows:
name: Build Windows
runs-on: windows-latest
env: { CI: true }
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: '18'
- name: Cache node modules
uses: actions/cache@v4
with:
path: |
\node_modules
%USERPROFILE%\.npm
key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
restore-keys: |
${{ runner.os }}-node-
- name: Install
shell: pwsh
run: npm ci
- name: Build frontend
shell: pwsh
run: npm run build-frontend
- name: Build Windows package
shell: pwsh
run: npm run build-w
- name: Upload Windows artifacts
uses: actions/upload-artifact@v4
with:
name: windows-dist
path: dist/**